// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIjOAMVxqa_KVQ77UIRp74EZ83ptKquKg',
    appId: '1:901994005057:web:fa3370a5201cc85316bcc0',
    messagingSenderId: '901994005057',
    projectId: 'portfolio-egb',
    authDomain: 'portfolio-egb.firebaseapp.com',
    storageBucket: 'portfolio-egb.appspot.com',
    measurementId: 'G-K8ZF73374T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUrZ7wYut0rCHXlY0jeZNQD1MGqewqm4o',
    appId: '1:901994005057:android:82f56da72f65295416bcc0',
    messagingSenderId: '901994005057',
    projectId: 'portfolio-egb',
    storageBucket: 'portfolio-egb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmxfZdgyKZmDCsmU8mv5Sdmht-9YZcNrI',
    appId: '1:901994005057:ios:bf501331a5b74a7d16bcc0',
    messagingSenderId: '901994005057',
    projectId: 'portfolio-egb',
    storageBucket: 'portfolio-egb.appspot.com',
    iosBundleId: 'com.example.portfolio947134',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmxfZdgyKZmDCsmU8mv5Sdmht-9YZcNrI',
    appId: '1:901994005057:ios:bf501331a5b74a7d16bcc0',
    messagingSenderId: '901994005057',
    projectId: 'portfolio-egb',
    storageBucket: 'portfolio-egb.appspot.com',
    iosBundleId: 'com.example.portfolio947134',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIjOAMVxqa_KVQ77UIRp74EZ83ptKquKg',
    appId: '1:901994005057:web:537b6c1e34cb76c316bcc0',
    messagingSenderId: '901994005057',
    projectId: 'portfolio-egb',
    authDomain: 'portfolio-egb.firebaseapp.com',
    storageBucket: 'portfolio-egb.appspot.com',
    measurementId: 'G-0H4JDXCK64',
  );
}
