name: Continuous Integration

on:
  workflow_run:
    workflows: [Run Test]
    types: 
      - completed
    branches:
      - main
      - 1-refine-code


jobs:
  build_web:
    name: Build Web
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0
      - run: flutter --version
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build web