name: Build

on:
  push:
    branches:
      - main
      - 1-refine-code

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.4.3
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web