name: Run Test

on:
  push:
    branches:
      - main
      - 1-refine-code

jobs:
  flutter_test:
    name: Flutter Tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test

  build_web:
    name: Build Web
    runs-on: ubuntu-latest
    needs: flutter_test

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0
      - run: flutter --version
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build web

  build_and_deploy:
    name: Deploy to Firebase Hosting on merge
    runs-on: ubuntu-latest
    needs: build_web

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0
      - run: flutter --version
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_EGB }}
          channelId: live
          projectId: portfolio-egb