name: Test Workflow

on:
  push:
    branches:
      - main
      - 1-refine-code

jobs:
    flutter_test:
        name: Flutter Tests
        runs-on: ubuntu-latest
    
        steps:
          - name: Clone repository
            uses: actions/checkout@v4
          - name: Set up Flutter
            uses: subosito/flutter-action@v2
            with:
              channel: stable
              flutter-version: 3.24.0
          - run: flutter --version
          - run: flutter pub get
          - run: flutter test
          - name: Debug output
            run: echo "Workflow completed successfully and ready to trigger next workflow."