name: Run Test

on:
  push:
    branches:
      - main
      - 1-refine-code

jobs:
    flutter_test:
        name: Flutter Tests
        runs-on: ubuntu-latest
    
        steps:
          - name: Clone repository
            uses: actions/checkout@v4
          - name: Set up Flutter
            uses: subosito/flutter-action@v2
            with:
              channel: stable
              flutter-version: 3.24.0
          - run: flutter --version
          - run: flutter pub get
          - run: flutter test
    
    build_web:
      name: Build Web
      runs-on: ubuntu-latest
        
      steps:
        - name: Clone repository
          uses: actions/checkout@v4
        - name: Set up Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: stable
            flutter-version: 3.24.0
        - run: flutter --version
        - run: flutter pub get
        - run: flutter clean
        - run: flutter build web
      
    deploy_web:
      name: Deploy to Firebase
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up Node.js
          uses: actions/setup-node@v2
          with: 
            node-version: 14
        - name: Install dependencies
          run: npm ci
        - name: Build
          run: npm run build
        - name: Deploy to Firebase
          uses: w9jds/firebase-action@master
          with:
            args: deploy --only hosting
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    